# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shapes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cshapes.proto\"\xf0\x01\n\x05Shape\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.Shape.Type\x12!\n\x08position\x18\x03 \x01(\x0b\x32\x0f.Shape.Position\x12\x19\n\x04size\x18\x04 \x01(\x0b\x32\x0b.Shape.Size\x12\x0f\n\x07visible\x18\x05 \x01(\x08\x1a \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x1a%\n\x04Size\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"(\n\x04Type\x12\n\n\x06SQUARE\x10\x00\x12\n\n\x06\x43IRCLE\x10\x01\x12\x08\n\x04LINE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shapes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SHAPE']._serialized_start=17
  _globals['_SHAPE']._serialized_end=257
  _globals['_SHAPE_POSITION']._serialized_start=144
  _globals['_SHAPE_POSITION']._serialized_end=176
  _globals['_SHAPE_SIZE']._serialized_start=178
  _globals['_SHAPE_SIZE']._serialized_end=215
  _globals['_SHAPE_TYPE']._serialized_start=217
  _globals['_SHAPE_TYPE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
